config/routes.rb
Todolist::Application.routes.draw do
  get "tables/index"
  get "tables/show"
  get "tables/new"
  get "tables/edit"
  get "tables/create"
  get "tables/update"
  get "tables/delete"
  get "tables/destroy"
  get "pages/about"
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was succesfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name,:importance,:urgency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    Copyright @ Azlan Shah A. Shafiuddin 2014
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a ><%= link_to "To Do List", tasks_path, class: 'navbar-brand' %></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Table View", tables_index_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Header -->
	<%= render 'layouts/header' %>

	<!-- Body content -->
	<div class="container">
		<%= yield %>
	</div>

	<!-- Footer -->
	<%= render 'layouts/footer' %>

	<!-- Javascript -->
	<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>A Rails project on To Do List using the Eisenhower Method</p>
<br>
<h1>How it works?</h1>

app/views/tables/create.html.erb
<h1>Tables#create</h1>
<p>Find me in app/views/tables/create.html.erb</p>

app/views/tables/delete.html.erb
<h1>Tables#delete</h1>
<p>Find me in app/views/tables/delete.html.erb</p>

app/views/tables/destroy.html.erb
<h1>Tables#destroy</h1>
<p>Find me in app/views/tables/destroy.html.erb</p>

app/views/tables/edit.html.erb
<h1>Tables#edit</h1>
<p>Find me in app/views/tables/edit.html.erb</p>

app/views/tables/index.html.erb
<h1>TABLE VIEW</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>  </th>
      <th>Urgent</th>
      <th>Not Urgent</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>Important</td>
      <td class="success">
        <% @tasks.each do |task| %>
          <% if task.importance == "Important" %>
            <% if task.urgency == "Urgent" %>
              <li>
                <%= task.name %>
              </li> 
            <% end %>
          <% end %>
        <% end %>
      </td>
      <td class="active">
        <% @tasks.each do |task| %>
          <% if task.importance == "Important" %>
            <% if task.urgency == "Not Urgent" %>
              <li>
                <%= task.name %>
              </li> 
            <% end %>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Not Important</td>
      <td class="warning">
        <% @tasks.each do |task| %>
          <% if task.importance == "Not Important" %>
            <% if task.urgency == "Urgent" %>
              <li>
                <%= task.name %>
              </li> 
            <% end %>
          <% end %>
        <% end %>
      </td>
      <td class="danger">
        <% @tasks.each do |task| %>
          <% if task.importance == "Not Important" %>
            <% if task.urgency == "Not Urgent" %>
              <li>
                <%= task.name %>
              </li> 
            <% end %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>

</table>

app/views/tables/new.html.erb
<h1>Tables#new</h1>
<p>Find me in app/views/tables/new.html.erb</p>

app/views/tables/show.html.erb
<h1>Tables#show</h1>
<p>Find me in app/views/tables/show.html.erb</p>

app/views/tables/update.html.erb
<h1>Tables#update</h1>
<p>Find me in app/views/tables/update.html.erb</p>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.label :importance %>
    <%= f.select(:importance, ["Important","Not Important"]) %>
    <%= f.label :urgency %>
    <%= f.select(:urgency, ["Urgent", "Not Urgent"]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task, class: "btn  btn-link" %> |
<%= link_to 'Back', tasks_path, class: "btn  btn-link" %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>THINGS TO DO</h1>

<%= link_to 'New Task', new_task_path, class: "btn  btn-link" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Settings</th>
      <th>Importance</th>
      <th>Urgency</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <!-- dropdown button -->
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit', edit_task_path(task) %></li>
              <li><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </td>
        <td><%= task.importance %></td>
        <td><%= task.urgency %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path, class: "btn  btn-link" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task), class: "btn  btn-link" %> |
<%= link_to 'Back', tasks_path, class: "btn  btn-link" %>